spring:
  application:
    name: banking-statistics-api

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate

# JWT Configuration (com√∫n para todos los entornos)
jwt:
  expiration: 86400000

# Server Configuration
server:
  port: 8080